[package]
name = "homebridge-rusty-spotify"
version = "0.1.0"
authors = ["anna <anna@scholtzan.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
